### DISCUSSION TITLE
GitHub ワークフローの中で、後続処理をキャンセルさせる方法

### DISCUSSION THREAD

**Discussion by dzeyelid** [dzeyelid/github-learning-playground#38] [Q&A] [answered]
公式ドキュメントでは、ワークフローの中で処理を切り換えるには、 `success` または `failure` で終えることしか紹介されてないように思う。下記のようにワークフロー全体を手動でキャンセルする方法はあるが、これは今回の用途には沿わない。

- [ワークフローをキャンセルする - GitHub Docs](https://docs.github.com/ja/actions/managing-workflow-runs/canceling-a-workflow)
- [アクションの終了コードの設定 - GitHub Docs](https://docs.github.com/ja/actions/creating-actions/setting-exit-codes-for-actions)

とはいえ、たとえば更新の可否をチェックして不要ならワークフローの後続処理は実行しないが失敗ではないケースもあり得るので、希望としては `skip` や `cancel` のようなステータスも扱ってほしいところ。 `needs` や `steps` には、 `conclusion` や `outcome` という処理結果を格納するプロパティがあるが、これは読み取りのみで設定する方法はなさそう。

- [`needs` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context)
- [`steps` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context)

どう処理させるのがきれいか、検討してみる。

**Comment by dzeyelid** [comment]
現時点ではこれがきれいかなと。

```yml
jobs:
  preprocess:
    name: Check pull request
    runs-on: ubuntu-latest
    outputs:
      SKIP: ${{ env.SKIP == 'true' }}  # シェルで設定した値は文字列なので、比較演算を行って Boolean に変換する
    steps:
      - name: Check first
        if: ${{ <check for a condition> }}
        run: |
          echo '::warning::This workflow does not need to run'
          echo 'SKIP=true' >> $GITHUB_ENV

      - name: Check second
        if: ${{ env.SKIP != 'true' && <check for another condition> }}
        run: |
          echo '::warning::This workflow does not need to run'
          echo 'SKIP=true' >> $GITHUB_ENV

  main-process:
    name: Main process
    needs:
      - preprocess
    if: ${{ ! fromJSON(needs.preprocess.outputs.SKIP) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "Process if necessary"
```

### References

- [`.github/workflows/generate.yml`](https://github.com/dzeyelid/github-actions-playground/blob/537d7578e2ef7bc70d9e9e9acce1e9b0d6ee3d06/.github/workflows/generate.yml)
  - [L18](https://github.com/dzeyelid/github-actions-playground/blob/537d7578e2ef7bc70d9e9e9acce1e9b0d6ee3d06/.github/workflows/generate.yml#L18)
  - [L26-L30](https://github.com/dzeyelid/github-actions-playground/blob/537d7578e2ef7bc70d9e9e9acce1e9b0d6ee3d06/.github/workflows/generate.yml#L26-L30)
  - [L32-L36](https://github.com/dzeyelid/github-actions-playground/blob/537d7578e2ef7bc70d9e9e9acce1e9b0d6ee3d06/.github/workflows/generate.yml#L32-L36)
  - 実行結果
    ![image](https://user-images.githubusercontent.com/977117/118393756-a1664980-b67b-11eb-98a0-6d5f7d64dc7e.png)

- [`.github/workflows/create-draft-release.yml`](https://github.com/dzeyelid/github-actions-playground/blob/537d7578e2ef7bc70d9e9e9acce1e9b0d6ee3d06/.github/workflows/create-draft-release.yml)
  - [L16-L28](https://github.com/dzeyelid/github-actions-playground/blob/537d7578e2ef7bc70d9e9e9acce1e9b0d6ee3d06/.github/workflows/create-draft-release.yml#L16-L28)
  - [L30-L34](https://github.com/dzeyelid/github-actions-playground/blob/537d7578e2ef7bc70d9e9e9acce1e9b0d6ee3d06/.github/workflows/create-draft-release.yml#L30-L34)
  - 実行結果
    ![image](https://user-images.githubusercontent.com/977117/118393784-c6f35300-b67b-11eb-9f1f-0c213618b58b.png)

**Reply by dzeyelid** [reply]
書いてから気づいたけれども、 `SKIP` じゃなくて、 `CONTINUE` のような肯定の文脈で扱った方がきれいですねw

**Reply by dzeyelid** [reply]
環境変数が設定されていない場合は `null` とみなされるが、これと別の値を `&&` で接続すると、 `null` に寄せられてしまうよう。

**Reply by dzeyelid** [reply]
`needs.<job id>.outputs.XXX` の値は `fromJson()` で処理しないと文字列。↑の場合は、 `needs.preprocess.outputs.SKIP` は `'true'` なので意図通りに動いているように見えたけど、`needs.preprocess.outputs.SKIP` に `false` （正確には `'false'` ）が入っていると意図した動きにならないので直す。

**Comment by dzeyelid** [comment, marked as answer]
否定の条件判定で `SKIP` させるのではなく、肯定条件で `CONTINUE` の可否を判定する構造に改善

```yml
jobs:
  preprocess:
    name: Check pull request
    runs-on: ubuntu-latest
    outputs:
      CONTINUE: ${{ env.CONTINUE != null && env.CONTINUE == 'true' }} # シェルで設定した値は文字列なので、比較演算を行って Boolean に変換する
    steps:
      - name: Check first
        if: ${{ <check for a condition> }}
        run: |
          echo 'CONTINUE=true' >> $GITHUB_ENV

      - name: Check second
         if: ${{ env.CONTINUE != 'true' && <check for another condition> }}
        run: |
          echo 'CONTINUE=true' >> $GITHUB_ENV

  mainProcess:
    name: Main process
    needs:
      - preprocess
    if: ${{ fromJSON(needs.preprocess.outputs.CONTINUE) }} # outputs の読み出しは文字列なので、 Boolean に変換する（二重で変換は気になるけれども🤔
```

- [.github/workflows/generate.yml](https://github.com/dzeyelid/github-actions-playground/blob/adc73a35aea1ca43191bdb62ebdb6b9d6d2e38d2/.github/workflows/generate.yml)
  - [L18](https://github.com/dzeyelid/github-actions-playground/blob/adc73a35aea1ca43191bdb62ebdb6b9d6d2e38d2/.github/workflows/generate.yml#L18)
  - [L26-L29](https://github.com/dzeyelid/github-actions-playground/blob/adc73a35aea1ca43191bdb62ebdb6b9d6d2e38d2/.github/workflows/generate.yml#L26-L29)
  - [L31-L35](https://github.com/dzeyelid/github-actions-playground/blob/adc73a35aea1ca43191bdb62ebdb6b9d6d2e38d2/.github/workflows/generate.yml#L31-L35)

- [.github/workflows/create-draft-release.yml](https://github.com/dzeyelid/github-actions-playground/blob/fd9c9bb573c68912302c1cb6e9c12ee14c34c8ba/.github/workflows/create-draft-release.yml)
  - [L19-L26](https://github.com/dzeyelid/github-actions-playground/blob/fd9c9bb573c68912302c1cb6e9c12ee14c34c8ba/.github/workflows/create-draft-release.yml#L19-L26)
  - [L28-L32](https://github.com/dzeyelid/github-actions-playground/blob/fd9c9bb573c68912302c1cb6e9c12ee14c34c8ba/.github/workflows/create-draft-release.yml#L28-L32)
  - [L46-L50](https://github.com/dzeyelid/github-actions-playground/blob/fd9c9bb573c68912302c1cb6e9c12ee14c34c8ba/.github/workflows/create-draft-release.yml#L46-L50)
